# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Telecom Foundation
email: fredguth@fredguth.com
description: > # this means to ignore newlines until "baseurl:"
  Our vision: A vibrant community using and enhancing the world's best open source real-time eventing and communications platform
description2: > # this means to ignore newlines until "baseurl:"
  Our mission: We build and use open source real-time communications software and encourage community cooperation and participation
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fredguth
github_username:  fredguth

sass:
  sass_dir: assets/styles/_sass

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
